LUNAR_IP = "172.20.10.2"  # Laptop A
EARTH_IP = "172.20.10.2"  # Laptop B
EARTH_RECEIVE_UPDATES_PORT = 5500    
EARTH_COMMAND_PORT = 5502    
EARTH_RECEIVE_SENSOR_DATA_PORT = 5501  

LUNAR_RECEIVE_PORT = 5503   
LUNAR_SEND_UPDATES_PORT = 5504    
LUNAR_SEND_SENSOR_DATA_PORT = 5505  


# Channel factors
MOON_TO_EARTH_LATENCY = 1.28  # seconds, one way delay
LATENCY_JITTER_FACTOR = 0.1 # Variation in travel time 
PACKET_LOSS_PROBABILITY = 0.05
PACKET_LOSS_FACTOR = 0.1


BANDWIDTH_LIMIT = 1024  # Bytes/second (simulating limited bandwidth)
PACKET_SIZE_LIMIT = 256  # Max payload size in bytes

# if UDP
MAX_RETRIES = 3 
